import { createSlice } from "@reduxjs/toolkit";
const roomsData = [
  {
    id: 101,
    type: "Super Deluxe",
    bedType: "King Bed",
    capacity: "2 Adults, 2 Children",
    status: "booked",
    guest: {
      name: "John Doe",
      address: "123 Elm Street, Springfield",
      phone: "+1-555-1234",
      email: "john.doe@example.com",
      checkIn: "2024-08-01",
      checkOut: "2024-08-07",
      bookingRef: "AB123CD456",
      specialRequests: "Late check-in requested, Extra towels",
    },
  },
  {
    id: 102,
    type: "Deluxe",
    bedType: "Queen Bed",
    capacity: "2 Adults",
    status: "available",
    guest: null,
  },
  {
    id: 103,
    type: "Standard",
    bedType: "Double Bed",
    capacity: "1 Adult",
    status: "available",
    guest: null,
  },
  {
    id: 104,
    type: "Deluxe",
    bedType: "King Bed",
    capacity: "2 Adults",
    status: "booked",
    guest: {
      name: "Jane Smith",
      address: "456 Oak Avenue, Boston",
      phone: "+1-555-5678",
      email: "jane.smith@example.com",
      checkIn: "2024-08-03",
      checkOut: "2024-08-10",
      bookingRef: "EF789GH012",
      specialRequests: "High floor preferred, Quiet room",
    },
  },
  {
    id: 105,
    type: "Standard",
    bedType: "Twin Beds",
    capacity: "2 Adults",
    status: "booked",
    guest: {
      name: "Michael Johnson",
      address: "789 Pine Road, Chicago",
      phone: "+1-555-9012",
      email: "michael.johnson@example.com",
      checkIn: "2024-08-05",
      checkOut: "2024-08-12",
      bookingRef: "IJ345KL678",
      specialRequests: "Non-smoking room, Extra pillows",
    },
  },
  {
    id: 106,
    type: "Suite",
    bedType: "King Bed + Sofa",
    capacity: "4 Adults",
    status: "available",
    guest: null,
  },
  {
    id: 107,
    type: "Super Deluxe",
    bedType: "Queen Bed",
    capacity: "2 Adults, 1 Child",
    status: "booked",
    guest: {
      name: "Sarah Williams",
      address: "321 Maple Drive, Los Angeles",
      phone: "+1-555-3456",
      email: "sarah.williams@example.com",
      checkIn: "2024-08-04",
      checkOut: "2024-08-09",
      bookingRef: "MN901OP234",
      specialRequests: "Baby crib required, Early check-in",
    },
  },
  {
    id: 108,
    type: "Deluxe",
    bedType: "Double Bed",
    capacity: "2 Adults",
    status: "available",
    guest: null,
  },
  {
    id: 109,
    type: "Standard",
    bedType: "Single Bed",
    capacity: "1 Adult",
    status: "booked",
    guest: {
      name: "Robert Brown",
      address: "654 Cedar Lane, Miami",
      phone: "+1-555-7890",
      email: "robert.brown@example.com",
      checkIn: "2024-08-06",
      checkOut: "2024-08-08",
      bookingRef: "QR567ST890",
      specialRequests: "Ground floor preferred, Late checkout",
    },
  },
  {
    id: 110,
    type: "Suite",
    bedType: "King Bed + Living Area",
    capacity: "3 Adults, 2 Children",
    status: "available",
    guest: null,
  },
  {
    id: 111,
    type: "Deluxe",
    bedType: "King Bed",
    capacity: "2 Adults",
    status: "booked",
    guest: {
      name: "Emily Davis",
      address: "987 Birch Street, Seattle",
      phone: "+1-555-2345",
      email: "emily.davis@example.com",
      checkIn: "2024-08-07",
      checkOut: "2024-08-14",
      bookingRef: "UV123WX456",
      specialRequests: "Ocean view, Mini-fridge required",
    },
  },
  {
    id: 112,
    type: "Standard",
    bedType: "Queen Bed",
    capacity: "2 Adults",
    status: "available",
    guest: null,
  },
  {
    id: 113,
    type: "Super Deluxe",
    bedType: "King Bed",
    capacity: "2 Adults, 2 Children",
    status: "booked",
    guest: {
      name: "Alice Green",
      address: "789 Willow Lane, Denver",
      phone: "+1-555-6789",
      email: "alice.green@example.com",
      checkIn: "2024-08-02",
      checkOut: "2024-08-08",
      bookingRef: "XY123ZT456",
      specialRequests: "Extra blankets, Balcony view",
    },
  },
  {
    id: 114,
    type: "Deluxe",
    bedType: "Queen Bed",
    capacity: "2 Adults",
    status: "available",
    guest: null,
  },
  {
    id: 115,
    type: "Standard",
    bedType: "Single Bed",
    capacity: "1 Adult",
    status: "booked",
    guest: {
      name: "Chris Taylor",
      address: "123 Aspen Road, Austin",
      phone: "+1-555-3457",
      email: "chris.taylor@example.com",
      checkIn: "2024-08-09",
      checkOut: "2024-08-11",
      bookingRef: "LM456NO789",
      specialRequests: "Early breakfast, Quiet room",
    },
  },
  {
    id: 116,
    type: "Suite",
    bedType: "King Bed + Sofa",
    capacity: "4 Adults",
    status: "available",
    guest: null,
  },
  {
    id: 117,
    type: "Super Deluxe",
    bedType: "Queen Bed",
    capacity: "2 Adults, 1 Child",
    status: "booked",
    guest: {
      name: "David Wilson",
      address: "456 Spruce Street, Orlando",
      phone: "+1-555-6780",
      email: "david.wilson@example.com",
      checkIn: "2024-08-10",
      checkOut: "2024-08-15",
      bookingRef: "OP123QR456",
      specialRequests: "Late checkout, Extra toiletries",
    },
  },
];

const initialState = {
  rooms: roomsData,
  filters: {
    type: "all",
    bedType: "all",
    status: "all",
  },
};
const roomSlice = createSlice({
  name: "RoomSlice",
  initialState,
  reducers: {
    setFilter: (state, action) => {
      state.filters = { ...state.filters, ...action.payload };
    },
    resetFilters: (state) => {
      state.rooms = roomsData;
      state.filters = {
        type: "all",
        bedType: "all",
        status: "all",
      };
    },
  },
});

export const { setFilter, resetFilters } = roomSlice.actions;

export default roomSlice.reducer;
