# Generated by Django 5.2 on 2025-07-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('buy_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sell_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('offer_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Offer Price is the price after discount', max_digits=10)),
                ('bv_price', models.IntegerField(default=0, help_text='Business Value Price')),
                ('stock', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
