# Generated by Django 5.2 on 2025-07-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_contactform_options_contactform_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('resolved', 'Resolved')], default='new', max_length=20),
        ),
    ]
