FROM python:3.12-slim

# Set environment vars
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DEBUG=True

# Install system dependencies
RUN apt-get update \
    && apt-get install -y \
        gcc \
        libpq-dev \
        python3-dev \
        build-essential \
    && apt-get clean


# Set working directory
WORKDIR /app

# Copy project files
COPY . .

# Install dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# collecting static files
# CMD ["sh", "-c", "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"]
CMD ["sh", "-c", "python manage.py migrate"]
CMD ["sh", "-c", "python manage.py collectstatic --noinput"]
CMD ["gunicorn", "project.wsgi:application", "--bind", "0.0.0.0:8000"]