
services:
  django-app:
    build:
      context: .                   # <== Build from the current directory (hms/)
      dockerfile: Dockerfile       # <== Dockerfile inside hms/
      args:
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
    container_name: hms-app
    volumes:
      - .:/app                      # <== Mount the current directory (hms/) into /app in the container
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - ./.env                     # <== Load environment variables from the .env file in the current directory (hms/)
    networks:
      - hms-network
    restart: always

  db:
    image: postgres:14
    container_name: hms-db
    environment:
      POSTGRES_DB: ${DBNAME}
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASSWORD}
    volumes:
      - ../database_data:/var/lib/postgresql/data  # <== Link to the database data folder outside of hms/
    networks:
      - hms-network
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:latest
    container_name: hms-redis
    volumes:
      - ../redis_data:/data         # <== Link to the redis data folder outside of hms/
    networks:
      - hms-network
    ports:
      - "6379:6379"
    restart: always

networks:
  hms-network:
    driver: bridge
