version: "3.9"

services:
  django-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: django-app
    volumes:
      - .:/app  # Mount the project directory
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - DJANGO_CACHE_LOCATION=/cache/django_cache
    networks:
      - bramhaputralottery-network
    restart: always


  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ../database_data:/var/lib/postgresql/data
    networks:
      - bramhaputralottery-network
    ports:
      - "5432:5432"
    restart: always

  celery:
    build:
      context: ./  # Set the build context to the current directory (bramhaputralottery)
      dockerfile: Dockerfile  # Path to your Dockerfile (relative to the context)
    container_name: celery-worker
    command: ["celery", "-A", "project.celery_app", "worker", "--loglevel=info"]
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - bramhaputralottery-network
    restart: always

networks:
  bramhaputralottery-network:
    driver: bridge

volumes:
  django_cache_data: