# Generated by Django 5.2 on 2025-07-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0002_remove_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_joinging_pakage',
            field=models.BooleanField(default=False),
        ),
    ]
