# Generated by Django 5.2 on 2025-07-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0003_user_address_user_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_prefix',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
