# Generated by Django 5.2 on 2025-07-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0004_user_id_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_prefix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
