# Generated by Django 5.2 on 2025-07-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0005_alter_user_id_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invite_tokens',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
