# Generated by Django 5.2 on 2025-07-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0006_user_invite_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invitation_chain_meta_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
