# Generated by Django 5.2 on 2025-07-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0007_user_invitation_chain_meta_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='direct_user_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
