# Generated by Django 5.2 on 2025-07-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0008_user_direct_user_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='direct_user_count',
        ),
        migrations.AlterField(
            model_name='user',
            name='achiver_level',
            field=models.PositiveBigIntegerField(blank=True, default=1, null=True),
        ),
    ]
