# Generated by Django 5.2 on 2025-07-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0009_remove_user_direct_user_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.TextField(default='USER'),
        ),
    ]
