# Generated by Django 5.2 on 2025-07-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0010_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='achiver_level',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
