# Generated by Django 5.2 on 2025-07-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0011_alter_user_achiver_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_distributer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
