# Generated by Django 5.2 on 2025-07-20 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0012_user_is_distributer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_distributer',
        ),
    ]
