# Generated by Django 5.2 on 2025-07-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0013_remove_user_is_distributer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='got_joining_package',
            field=models.BooleanField(default=False),
        ),
    ]
